; OpenRA2 campaign list
; First 32 = Fusion (China/Allies/Soviet/Yuri). Then Official RA2+YR.
[Missions]
Mission=mission01.ini
Mission=mission02.ini
Mission=mission03.ini
Mission=mission04.ini
Mission=mission05.ini
Mission=mission06.ini
Mission=mission07.ini
Mission=mission08.ini
Mission=mission09.ini
Mission=mission10.ini
Mission=mission11.ini
Mission=mission12.ini
Mission=mission13.ini
Mission=mission14.ini
Mission=mission15.ini
Mission=mission16.ini
Mission=mission17.ini
Mission=mission18.ini
Mission=mission19.ini
Mission=mission20.ini
Mission=mission21.ini
Mission=mission22.ini
Mission=mission23.ini
Mission=mission24.ini
Mission=mission25.ini
Mission=mission26.ini
Mission=mission27.ini
Mission=mission28.ini
Mission=mission29.ini
Mission=mission30.ini
Mission=mission31.ini
Mission=mission32.ini
Mission=official/oa01.ini
Mission=official/oa02.ini
Mission=official/oa03.ini
Mission=official/oa04.ini
Mission=official/oa05.ini
Mission=official/oa06.ini
Mission=official/oa07.ini
Mission=official/oa08.ini
Mission=official/oa09.ini
Mission=official/oa10.ini
Mission=official/oa11.ini
Mission=official/oa12.ini
Mission=official/os01.ini
Mission=official/os02.ini
Mission=official/os03.ini
Mission=official/os04.ini
Mission=official/os05.ini
Mission=official/os06.ini
Mission=official/os07.ini
Mission=official/os08.ini
Mission=official/os09.ini
Mission=official/os10.ini
Mission=official/os11.ini
Mission=official/os12.ini
Mission=official/ya01.ini
Mission=official/ya02.ini
Mission=official/ya03.ini
Mission=official/ya04.ini
Mission=official/ya05.ini
Mission=official/ya06.ini
Mission=official/ya07.ini
Mission=official/ys01.ini
Mission=official/ys02.ini
Mission=official/ys03.ini
Mission=official/ys04.ini
Mission=official/ys05.ini
Mission=official/ys06.ini
Mission=official/ys07.ini
