; Full scripted: Red Advance
[General]
Name=红色推进
NameEn=Red Advance
Brief=推进摧毁盟军前哨。
BriefEn=Advance; destroy Allied outpost.
Faction=Soviet
AI=Allies
MapSize=96
MapType=0
Money=9000
Objective=2
ObjectiveTick=0
MapFile=maps/fusion/mission17.txt
NoStartForce=yes
Track=0
LineId=fs
LineIndex=0
Country=Russia
WinOnAllPrimary=yes
Phase=0
AllowedBuildings=ConYard,TeslaReactor,Barracks,OreRefinery,SentryGun,Wall,WarFactory,NavalYard,Radar,BattleLab,TeslaCoil,FlakCannon,IronCurtain,NukeSilo,ServiceDepot,BattleBunker,TankBunker
AllowedUnits=MCV,Harvester,WarMiner,Conscript,Engineer,AttackDog,FlakTrooper,TeslaTrooper,Rhino,FlakTrack,V3Launcher,Apocalypse,Kirov,Dreadnought,Typhoon,AmphTransport,Boris,Desolator,TerrorDrone,SeaScorpion

[Objective.1]
Text=推进摧毁盟军前哨。
TextEn=Advance; destroy Allied outpost.
Primary=yes
GateWin=yes

[Trig.1]
Cond=Always
Act=Objective
Msg=推进摧毁盟军前哨。
MsgEn=Advance; destroy Allied outpost.

[Trig.2]
Cond=Always
Act=Eva
Msg=推进摧毁盟军前哨。
MsgEn=Advance; destroy Allied outpost.

[Trig.3]
Cond=Always
Act=SetPhase
A0=1

[Trig.4]
Cond=PlayerAllDead
Act=Lose
C0=0
Msg=我军覆灭。
MsgEn=Our forces destroyed.

[Trig.5]
Cond=PlayerBldLost
Act=CompleteObj
C0=1
BType=ConYard
A0=0
Msg=指挥部摧毁！
MsgEn=HQ destroyed!

[Trig.6]
Cond=Time
Act=Reinforce
C0=3600
A0=1
A1=1
A2=60
A3=40
Units=GI,IFV,Grizzly
Once=yes

[Wave.1]
At=2700
Units=GI,Grizzly

[Wave.2]
At=6300
Units=GI,IFV,Grizzly

[Wave.3]
At=10800
Units=PrismTank,Rocketeer

