; Full scripted: Civil Spark
[General]
Name=内战火花
NameEn=Civil Spark
Brief=摧毁叛军尤里节点。
BriefEn=Destroy rebel Yuri node.
BriefArt=assets/sprites/bld_psychicbeacon.png
Faction=Soviet
AI=Yuri
MapSize=96
MapType=0
Money=12500
Objective=2
ObjectiveTick=0
MapFile=maps/fusion/mission23.txt
NoStartForce=yes
Track=0
LineId=fs
LineIndex=6
Country=Russia
WinOnAllPrimary=yes
Phase=0
AllowedBuildings=ConYard,TeslaReactor,Barracks,OreRefinery,SentryGun,Wall,WarFactory,NavalYard,Radar,BattleLab,TeslaCoil,FlakCannon,IronCurtain,NukeSilo,ServiceDepot,BattleBunker,TankBunker
AllowedUnits=MCV,Harvester,WarMiner,Conscript,Engineer,AttackDog,FlakTrooper,TeslaTrooper,Rhino,FlakTrack,V3Launcher,Apocalypse,Kirov,Dreadnought,Typhoon,AmphTransport,Boris,Desolator,TerrorDrone,SeaScorpion

[Objective.1]
Text=摧毁叛军尤里节点。
TextEn=Destroy rebel Yuri node.
Primary=yes
GateWin=yes

[Objective.2]
Text=摧毁敌军指挥部
TextEn=Destroy enemy HQ
Primary=yes
GateWin=yes

[Trig.1]
Cond=Always
Act=Objective
Msg=摧毁叛军尤里节点。
MsgEn=Destroy rebel Yuri node.

[Trig.2]
Cond=Always
Act=Eva
Msg=摧毁叛军尤里节点。
MsgEn=Destroy rebel Yuri node.

[Trig.3]
Cond=Always
Act=SetPhase
A0=1

[Trig.4]
Cond=PlayerAllDead
Act=Lose
C0=0
Msg=我军覆灭。
MsgEn=Our forces destroyed.

[Trig.5]
Cond=PlayerBldLost
Act=CompleteObj
C0=1
BType=PsychicBeacon
A0=0
Msg=主要目标摧毁！
MsgEn=Primary destroyed!

[Trig.6]
Cond=PlayerBldLost
Act=SetPhase
C0=1
BType=PsychicBeacon
A0=2

[Trig.7]
Cond=PlayerBldLost
Act=CompleteObj
C0=1
BType=ConYard
A0=1
RequiresPhase=2
Msg=敌军肃清！
MsgEn=Enemy cleared!

[Trig.8]
Cond=Time
Act=Reinforce
C0=3600
A0=1
A1=1
A2=60
A3=40
Units=Initiate,Brute,GatlingTank
Once=yes

[Wave.1]
At=2700
Units=Initiate,LasherTank

[Wave.2]
At=6300
Units=Initiate,Brute,GatlingTank

[Wave.3]
At=10800
Units=Yuri,Magnetron

