; Full scripted: Psi Awaken
[General]
Name=心灵觉醒
NameEn=Psi Awaken
Brief=建立尤里力量摧毁盟军前哨。
BriefEn=Raise Yuri; destroy Allied outpost.
Faction=Yuri
AI=Allies
MapSize=96
MapType=0
Money=9000
Objective=2
ObjectiveTick=0
MapFile=maps/fusion/mission25.txt
NoStartForce=yes
Track=0
LineId=fy
LineIndex=0
Country=Yuri
WinOnAllPrimary=yes
Phase=0
AllowedBuildings=ConYard,BioReactor,Barracks,OreRefinery,Wall,WarFactory,NavalYard,PsychicSensor,BattleLab,PsychicTower,GatlingCannon,CloningVat,PsychicDominator,Grinder,GeneticMutator
AllowedUnits=MCV,SlaveMiner,Initiate,Engineer,Brute,Virus,Yuri,LasherTank,GatlingTank,Magnetron,MasterMind,FloatingDisc,Boomer,AmphTransport,ChaosDrone

[Objective.1]
Text=建立尤里力量摧毁盟军前哨。
TextEn=Raise Yuri; destroy Allied outpost.
Primary=yes
GateWin=yes

[Trig.1]
Cond=Always
Act=Objective
Msg=建立尤里力量摧毁盟军前哨。
MsgEn=Raise Yuri; destroy Allied outpost.

[Trig.2]
Cond=Always
Act=Eva
Msg=建立尤里力量摧毁盟军前哨。
MsgEn=Raise Yuri; destroy Allied outpost.

[Trig.3]
Cond=Always
Act=SetPhase
A0=1

[Trig.4]
Cond=PlayerAllDead
Act=Lose
C0=0
Msg=我军覆灭。
MsgEn=Our forces destroyed.

[Trig.5]
Cond=PlayerBldLost
Act=CompleteObj
C0=1
BType=ConYard
A0=0
Msg=指挥部摧毁！
MsgEn=HQ destroyed!

[Trig.6]
Cond=Time
Act=Reinforce
C0=3600
A0=1
A1=1
A2=60
A3=40
Units=GI,IFV,Grizzly
Once=yes

[Wave.1]
At=2700
Units=GI,Grizzly

[Wave.2]
At=6300
Units=GI,IFV,Grizzly

[Wave.3]
At=10800
Units=PrismTank,Rocketeer

