; Full scripted: Beacon Deploy
[General]
Name=信标部署
NameEn=Beacon Deploy
Brief=部署攻势摧毁敌军指挥部。
BriefEn=Push and destroy enemy HQ.
Faction=Yuri
AI=Allies
MapSize=96
MapType=0
Money=9500
Objective=2
ObjectiveTick=0
MapFile=maps/fusion/mission26.txt
NoStartForce=yes
Track=0
LineId=fy
LineIndex=1
Country=Yuri
WinOnAllPrimary=yes
Phase=0
AllowedBuildings=ConYard,BioReactor,Barracks,OreRefinery,Wall,WarFactory,NavalYard,PsychicSensor,BattleLab,PsychicTower,GatlingCannon,CloningVat,PsychicDominator,Grinder,GeneticMutator
AllowedUnits=MCV,SlaveMiner,Initiate,Engineer,Brute,Virus,Yuri,LasherTank,GatlingTank,Magnetron,MasterMind,FloatingDisc,Boomer,AmphTransport,ChaosDrone

[Objective.1]
Text=部署攻势摧毁敌军指挥部。
TextEn=Push and destroy enemy HQ.
Primary=yes
GateWin=yes

[Trig.1]
Cond=Always
Act=Objective
Msg=部署攻势摧毁敌军指挥部。
MsgEn=Push and destroy enemy HQ.

[Trig.2]
Cond=Always
Act=Eva
Msg=部署攻势摧毁敌军指挥部。
MsgEn=Push and destroy enemy HQ.

[Trig.3]
Cond=Always
Act=SetPhase
A0=1

[Trig.4]
Cond=PlayerAllDead
Act=Lose
C0=0
Msg=我军覆灭。
MsgEn=Our forces destroyed.

[Trig.5]
Cond=PlayerBldLost
Act=CompleteObj
C0=1
BType=ConYard
A0=0
Msg=指挥部摧毁！
MsgEn=HQ destroyed!

[Trig.6]
Cond=Time
Act=Reinforce
C0=3600
A0=1
A1=1
A2=60
A3=40
Units=GI,IFV,Grizzly
Once=yes

[Wave.1]
At=2700
Units=GI,Grizzly

[Wave.2]
At=6300
Units=GI,IFV,Grizzly

[Wave.3]
At=10800
Units=PrismTank,Rocketeer

