; Full scripted: Deep Sea
[General]
Name=深海
NameEn=Deep Sea
Brief=摧毁苏军船坞与指挥部，肃清珍珠港海域。
BriefEn=Destroy Soviet Naval Yard and HQ at Pearl Harbor.
Faction=Allies
AI=Soviet
MapSize=96
MapType=0
Money=13000
Objective=2
ObjectiveTick=0
MapFile=maps/official/oa07.txt
NoStartForce=yes
Track=1
LineId=oa
LineIndex=6
Country=America
WinOnAllPrimary=yes
Phase=0
AllowedBuildings=ConYard,PowerPlant,Barracks,OreRefinery,Pillbox,Wall,WarFactory,NavalYard,Radar,AirForceCmd,PrismTower,PatriotMissile,BattleLab,OrePurifier,ServiceDepot,GapGenerator,SpySat,ChronoSphere
AllowedUnits=MCV,Harvester,ChronoMiner,GI,Engineer,AttackDog,Grizzly,Destroyer,AmphTransport,Tanya,NavySEAL,Spy,GuardianGI,IFV,PrismTank,Rocketeer,Intruder,Nighthawk,Aegis,AircraftCarrier,Sniper,Chrono,MirageTank

[Objective.1]
Text=摧毁苏军船坞
TextEn=Destroy Naval Yard
Primary=yes
GateWin=yes

[Objective.2]
Text=摧毁苏军指挥部
TextEn=Destroy Soviet HQ
Primary=yes
GateWin=yes

[Trig.1]
Cond=Always
Act=Objective
Msg=摧毁苏军船坞与指挥部，肃清珍珠港海域。
MsgEn=Destroy Soviet Naval Yard and HQ at Pearl Harbor.

[Trig.2]
Cond=Always
Act=Eva
Msg=摧毁苏军船坞与指挥部，肃清珍珠港海域。
MsgEn=Destroy Soviet Naval Yard and HQ at Pearl Harbor.

[Trig.3]
Cond=Always
Act=SetPhase
A0=1

[Trig.4]
Cond=PlayerAllDead
Act=Lose
C0=0
Msg=我军覆灭。
MsgEn=Our forces destroyed.

[Trig.5]
Cond=PlayerBldLost
Act=CompleteObj
C0=1
BType=NavalYard
A0=0
Msg=船坞已毁！
MsgEn=Yard down!

[Trig.6]
Cond=PlayerBldLost
Act=SetPhase
C0=1
BType=NavalYard
A0=2

[Trig.7]
Cond=PlayerBldLost
Act=CompleteObj
C0=1
BType=ConYard
A0=1
RequiresPhase=2
Msg=海域肃清！
MsgEn=Seas cleared!

[Trig.8]
Cond=Time
Act=Reinforce
C0=2400
A0=1
A1=1
A2=74
A3=74
Units=Dreadnought,SeaScorpion
Once=yes

