; Full scripted: Red Dawn
[General]
Name=红色黎明
NameEn=Red Dawn
Brief=华盛顿：摧毁五角大楼盟军指挥部。
BriefEn=Washington: destroy the Pentagon HQ.
Faction=Soviet
AI=Allies
MapSize=96
MapType=0
Money=8000
Objective=2
ObjectiveTick=0
MapFile=maps/official/os01.txt
NoStartForce=yes
Track=1
LineId=os
LineIndex=0
Country=Russia
WinOnAllPrimary=yes
Phase=0
AllowedBuildings=SentryGun,Wall
AllowedUnits=Conscript,Engineer,AttackDog,FlakTrooper,TeslaTrooper,Rhino

[Objective.1]
Text=摧毁五角大楼指挥部
TextEn=Destroy Pentagon HQ
Primary=yes
GateWin=yes

[Trig.1]
Cond=Always
Act=Objective
Msg=华盛顿：摧毁五角大楼盟军指挥部。
MsgEn=Washington: destroy the Pentagon HQ.

[Trig.2]
Cond=Always
Act=Eva
Msg=华盛顿：摧毁五角大楼盟军指挥部。
MsgEn=Washington: destroy the Pentagon HQ.

[Trig.3]
Cond=Always
Act=SetPhase
A0=1

[Trig.4]
Cond=PlayerAllDead
Act=Lose
C0=0
Msg=我军覆灭。
MsgEn=Our forces destroyed.

[Trig.5]
Cond=PlayerBldLost
Act=CompleteObj
C0=1
BType=ConYard
A0=0
Msg=五角大楼陷落！
MsgEn=Pentagon fallen!

[Trig.6]
Cond=Time
Act=Reinforce
C0=1800
A0=1
A1=1
A2=50
A3=50
Units=GI,Grizzly
Once=yes

