; Full scripted: Hostile Shore
[General]
Name=敌对海岸
NameEn=Hostile Shore
Brief=佛罗里达：建立立足点并摧毁盟军指挥部。
BriefEn=Florida: beachhead and destroy Allied HQ.
Faction=Soviet
AI=Allies
MapSize=96
MapType=0
Money=10000
Objective=2
ObjectiveTick=0
MapFile=maps/official/os02.txt
NoStartForce=yes
Track=1
LineId=os
LineIndex=1
Country=Russia
WinOnAllPrimary=yes
Phase=0
AllowedBuildings=ConYard,TeslaReactor,Barracks,OreRefinery,SentryGun,Wall,WarFactory,NavalYard,Radar,BattleLab,TeslaCoil,FlakCannon,IronCurtain,NukeSilo,ServiceDepot,BattleBunker,TankBunker
AllowedUnits=MCV,Harvester,WarMiner,Conscript,Engineer,AttackDog,FlakTrooper,TeslaTrooper,Rhino,FlakTrack,V3Launcher,Apocalypse,Kirov,Dreadnought,Typhoon,AmphTransport,Boris,Desolator,TerrorDrone,SeaScorpion

[Objective.1]
Text=摧毁盟军指挥部
TextEn=Destroy Allied HQ
Primary=yes
GateWin=yes

[Trig.1]
Cond=Always
Act=Objective
Msg=佛罗里达：建立立足点并摧毁盟军指挥部。
MsgEn=Florida: beachhead and destroy Allied HQ.

[Trig.2]
Cond=Always
Act=Eva
Msg=佛罗里达：建立立足点并摧毁盟军指挥部。
MsgEn=Florida: beachhead and destroy Allied HQ.

[Trig.3]
Cond=Always
Act=SetPhase
A0=1

[Trig.4]
Cond=PlayerAllDead
Act=Lose
C0=0
Msg=我军覆灭。
MsgEn=Our forces destroyed.

[Trig.5]
Cond=PlayerBldLost
Act=CompleteObj
C0=1
BType=ConYard
A0=0
Msg=立足点巩固！
MsgEn=Beachhead secured!

[Trig.6]
Cond=Time
Act=Reinforce
C0=2400
A0=1
A1=0
A2=40
A3=20
Units=GI,Grizzly,IFV
Once=yes

