; Full scripted: Big Apple
[General]
Name=大苹果
NameEn=Big Apple
Brief=纽约：占领美国Battle Lab并摧毁盟军指挥部。
BriefEn=NY: capture Battle Lab and destroy Allied HQ.
Faction=Soviet
AI=Allies
MapSize=96
MapType=0
Money=11000
Objective=2
ObjectiveTick=0
MapFile=maps/official/os03.txt
NoStartForce=yes
Track=1
LineId=os
LineIndex=2
Country=Russia
WinOnAllPrimary=yes
Phase=0
AllowedBuildings=ConYard,TeslaReactor,Barracks,OreRefinery,SentryGun,Wall,WarFactory,NavalYard,Radar,BattleLab,TeslaCoil,FlakCannon,IronCurtain,NukeSilo,ServiceDepot,BattleBunker,TankBunker
AllowedUnits=MCV,Harvester,WarMiner,Conscript,Engineer,AttackDog,FlakTrooper,TeslaTrooper,Rhino,FlakTrack,V3Launcher,Apocalypse,Kirov,Dreadnought,Typhoon,AmphTransport,Boris,Desolator,TerrorDrone,SeaScorpion

[Objective.1]
Text=占领盟军实验室
TextEn=Capture Allied Battle Lab
Primary=yes
GateWin=yes

[Objective.2]
Text=摧毁盟军指挥部
TextEn=Destroy Allied HQ
Primary=yes
GateWin=yes

[Trig.1]
Cond=Always
Act=Objective
Msg=纽约：占领美国Battle Lab并摧毁盟军指挥部。
MsgEn=NY: capture Battle Lab and destroy Allied HQ.

[Trig.2]
Cond=Always
Act=Eva
Msg=纽约：占领美国Battle Lab并摧毁盟军指挥部。
MsgEn=NY: capture Battle Lab and destroy Allied HQ.

[Trig.3]
Cond=Always
Act=SetPhase
A0=1

[Trig.4]
Cond=PlayerAllDead
Act=Lose
C0=0
Msg=我军覆灭。
MsgEn=Our forces destroyed.

[Trig.5]
Cond=BldCaptured
Act=CompleteObj
C0=0
C2=1
BType=BattleLab
A0=0
Msg=实验室已夺！
MsgEn=Lab captured!

[Trig.6]
Cond=BldCaptured
Act=SetPhase
C0=0
C2=1
BType=BattleLab
A0=2

[Trig.7]
Cond=PlayerBldLost
Act=CompleteObj
C0=1
BType=ConYard
A0=1
RequiresPhase=2
Msg=纽约沦陷！
MsgEn=NY fallen!

