; Full scripted: Home Front
[General]
Name=祖国前线
NameEn=Home Front
Brief=符拉迪沃斯托克：保卫本土，摧毁入侵盟军。
BriefEn=Vladivostok: defend homeland, destroy Allied invaders.
Faction=Soviet
AI=Allies
MapSize=96
MapType=0
Money=12000
Objective=2
ObjectiveTick=0
MapFile=maps/official/os04.txt
NoStartForce=yes
Track=1
LineId=os
LineIndex=3
Country=Russia
WinOnAllPrimary=yes
Phase=0
AllowedBuildings=ConYard,TeslaReactor,Barracks,OreRefinery,SentryGun,Wall,WarFactory,NavalYard,Radar,BattleLab,TeslaCoil,FlakCannon,IronCurtain,NukeSilo,ServiceDepot,BattleBunker,TankBunker
AllowedUnits=MCV,Harvester,WarMiner,Conscript,Engineer,AttackDog,FlakTrooper,TeslaTrooper,Rhino,FlakTrack,V3Launcher,Apocalypse,Kirov,Dreadnought,Typhoon,AmphTransport,Boris,Desolator,TerrorDrone,SeaScorpion

[Objective.1]
Text=摧毁盟军指挥部
TextEn=Destroy Allied HQ
Primary=yes
GateWin=yes

[Trig.1]
Cond=Always
Act=Objective
Msg=符拉迪沃斯托克：保卫本土，摧毁入侵盟军。
MsgEn=Vladivostok: defend homeland, destroy Allied invaders.

[Trig.2]
Cond=Always
Act=Eva
Msg=符拉迪沃斯托克：保卫本土，摧毁入侵盟军。
MsgEn=Vladivostok: defend homeland, destroy Allied invaders.

[Trig.3]
Cond=Always
Act=SetPhase
A0=1

[Trig.4]
Cond=PlayerAllDead
Act=Lose
C0=0
Msg=我军覆灭。
MsgEn=Our forces destroyed.

[Trig.5]
Cond=PlayerBldLost
Act=CompleteObj
C0=1
BType=ConYard
A0=0
Msg=入侵击退！
MsgEn=Invasion broken!

[Trig.6]
Cond=Time
Act=Reinforce
C0=2000
A0=1
A1=0
A2=50
A3=40
Units=GI,Grizzly,Chrono
Once=yes

[Trig.7]
Cond=Time
Act=Reinforce
C0=4500
A0=1
A1=1
A2=60
A3=50
Units=PrismTank,Rocketeer
Once=yes

