; Full scripted: The Fox and the Hound
[General]
Name=狐与猎犬
NameEn=The Fox and the Hound
Brief=圣安东尼奥：摧毁尤里心灵信标节点。
BriefEn=San Antonio: destroy Yuri Psychic Beacon.
BriefArt=assets/sprites/bld_psychicbeacon.png
Faction=Soviet
AI=Yuri
MapSize=96
MapType=0
Money=13500
Objective=2
ObjectiveTick=0
MapFile=maps/official/os09.txt
NoStartForce=yes
Track=1
LineId=os
LineIndex=8
Country=Russia
WinOnAllPrimary=yes
Phase=0
AllowedBuildings=ConYard,TeslaReactor,Barracks,OreRefinery,SentryGun,Wall,WarFactory,NavalYard,Radar,BattleLab,TeslaCoil,FlakCannon,IronCurtain,NukeSilo,ServiceDepot,BattleBunker,TankBunker
AllowedUnits=MCV,Harvester,WarMiner,Conscript,Engineer,AttackDog,FlakTrooper,TeslaTrooper,Rhino,FlakTrack,V3Launcher,Apocalypse,Kirov,Dreadnought,Typhoon,AmphTransport,Boris,Desolator,TerrorDrone,SeaScorpion

[Objective.1]
Text=摧毁心灵信标
TextEn=Destroy Psychic Beacon
Primary=yes
GateWin=yes

[Objective.2]
Text=摧毁尤里指挥部
TextEn=Destroy Yuri HQ
Primary=yes
GateWin=yes

[Trig.1]
Cond=Always
Act=Objective
Msg=圣安东尼奥：摧毁尤里心灵信标节点。
MsgEn=San Antonio: destroy Yuri Psychic Beacon.

[Trig.2]
Cond=Always
Act=Eva
Msg=圣安东尼奥：摧毁尤里心灵信标节点。
MsgEn=San Antonio: destroy Yuri Psychic Beacon.

[Trig.3]
Cond=Always
Act=SetPhase
A0=1

[Trig.4]
Cond=PlayerAllDead
Act=Lose
C0=0
Msg=我军覆灭。
MsgEn=Our forces destroyed.

[Trig.5]
Cond=PlayerBldLost
Act=CompleteObj
C0=1
BType=PsychicBeacon
A0=0
Msg=信标摧毁！
MsgEn=Beacon destroyed!

[Trig.6]
Cond=PlayerBldLost
Act=SetPhase
C0=1
BType=PsychicBeacon
A0=2

[Trig.7]
Cond=PlayerBldLost
Act=CompleteObj
C0=1
BType=ConYard
A0=1
RequiresPhase=2
Msg=尤里溃败！
MsgEn=Yuri broken!

