; Full scripted: Weathered Alliance
[General]
Name=风雨同盟
NameEn=Weathered Alliance
Brief=维尔京群岛：摧毁盟军天气控制器。
BriefEn=Virgin Islands: destroy Weather Control Device.
Faction=Soviet
AI=Allies
MapSize=96
MapType=0
Money=14000
Objective=2
ObjectiveTick=0
MapFile=maps/official/os10.txt
NoStartForce=yes
Track=1
LineId=os
LineIndex=9
Country=Russia
WinOnAllPrimary=yes
Phase=0
AllowedBuildings=ConYard,TeslaReactor,Barracks,OreRefinery,SentryGun,Wall,WarFactory,NavalYard,Radar,BattleLab,TeslaCoil,FlakCannon,IronCurtain,NukeSilo,ServiceDepot,BattleBunker,TankBunker
AllowedUnits=MCV,Harvester,WarMiner,Conscript,Engineer,AttackDog,FlakTrooper,TeslaTrooper,Rhino,FlakTrack,V3Launcher,Apocalypse,Kirov,Dreadnought,Typhoon,AmphTransport,Boris,Desolator,TerrorDrone,SeaScorpion

[Objective.1]
Text=摧毁天气控制器
TextEn=Destroy Weather Device
Primary=yes
GateWin=yes

[Trig.1]
Cond=Always
Act=Objective
Msg=维尔京群岛：摧毁盟军天气控制器。
MsgEn=Virgin Islands: destroy Weather Control Device.

[Trig.2]
Cond=Always
Act=Eva
Msg=维尔京群岛：摧毁盟军天气控制器。
MsgEn=Virgin Islands: destroy Weather Control Device.

[Trig.3]
Cond=Always
Act=SetPhase
A0=1

[Trig.4]
Cond=PlayerAllDead
Act=Lose
C0=0
Msg=我军覆灭。
MsgEn=Our forces destroyed.

[Trig.5]
Cond=BldCaptured
Act=RevealMap
C0=0
C2=1
BType=BattleLab
A0=0
A1=70
A2=20
A3=16
Msg=定位完成！
MsgEn=Located!

[Trig.6]
Cond=PlayerBldLost
Act=CompleteObj
C0=1
BType=WeatherDevice
A0=0
Msg=天气控制器摧毁！
MsgEn=Weather Device down!

[Trig.7]
Cond=Time
Act=Reinforce
C0=3000
A0=1
A1=1
A2=70
A3=30
Units=PrismTank,GI
Once=yes

