; Full scripted: Red Revolution
[General]
Name=红色革命
NameEn=Red Revolution
Brief=莫斯科：摧毁尤里克里姆林宫总部。鲍里斯存活。
BriefEn=Moscow: destroy Yuri Kremlin HQ. Boris lives.
Faction=Soviet
AI=Yuri
MapSize=96
MapType=0
Money=14500
Objective=2
ObjectiveTick=0
MapFile=maps/official/os11.txt
NoStartForce=yes
Track=1
LineId=os
LineIndex=10
Country=Russia
WinOnAllPrimary=yes
Phase=0
AllowedBuildings=ConYard,TeslaReactor,Barracks,OreRefinery,SentryGun,Wall,WarFactory,NavalYard,Radar,BattleLab,TeslaCoil,FlakCannon,IronCurtain,NukeSilo,ServiceDepot,BattleBunker,TankBunker
AllowedUnits=MCV,Harvester,WarMiner,Conscript,Engineer,AttackDog,FlakTrooper,TeslaTrooper,Rhino,FlakTrack,V3Launcher,Apocalypse,Kirov,Dreadnought,Typhoon,AmphTransport,Boris,Desolator,TerrorDrone,SeaScorpion

[Objective.1]
Text=摧毁尤里总部
TextEn=Destroy Yuri HQ
Primary=yes
GateWin=yes

[Objective.2]
Text=鲍里斯存活
TextEn=Boris lives
Primary=yes
GateWin=no

[Trig.1]
Cond=Always
Act=Objective
Msg=莫斯科：摧毁尤里克里姆林宫总部。鲍里斯存活。
MsgEn=Moscow: destroy Yuri Kremlin HQ. Boris lives.

[Trig.2]
Cond=Always
Act=Eva
Msg=莫斯科：摧毁尤里克里姆林宫总部。鲍里斯存活。
MsgEn=Moscow: destroy Yuri Kremlin HQ. Boris lives.

[Trig.3]
Cond=Always
Act=SetPhase
A0=1

[Trig.4]
Cond=PlayerAllDead
Act=Lose
C0=0
Msg=我军覆灭。
MsgEn=Our forces destroyed.

[Trig.5]
Cond=UnitLost
Act=Lose
C0=0
CType=Boris
Msg=Boris阵亡。
MsgEn=Boris fallen.

[Trig.6]
Cond=PlayerBldLost
Act=CompleteObj
C0=1
BType=ConYard
A0=0
Msg=尤里总部摧毁！
MsgEn=Yuri HQ destroyed!

[Trig.7]
Cond=Time
Act=Reinforce
C0=2400
A0=1
A1=1
A2=50
A3=40
Units=Initiate,LasherTank,Yuri
Once=yes

