; Full scripted: Polar Storm
[General]
Name=极地风暴
NameEn=Polar Storm
Brief=阿拉斯加：摧毁盟军超时空仪。
BriefEn=Alaska: destroy Allied Chronosphere.
BriefArt=assets/sprites/bld_timemachine.png
Faction=Soviet
AI=Allies
MapSize=96
MapType=0
Money=15000
Objective=2
ObjectiveTick=0
MapFile=maps/official/os12.txt
NoStartForce=yes
Track=1
LineId=os
LineIndex=11
Country=Russia
WinOnAllPrimary=yes
Phase=0
AllowedBuildings=ConYard,TeslaReactor,Barracks,OreRefinery,SentryGun,Wall,WarFactory,NavalYard,Radar,BattleLab,TeslaCoil,FlakCannon,IronCurtain,NukeSilo,ServiceDepot,BattleBunker,TankBunker
AllowedUnits=MCV,Harvester,WarMiner,Conscript,Engineer,AttackDog,FlakTrooper,TeslaTrooper,Rhino,FlakTrack,V3Launcher,Apocalypse,Kirov,Dreadnought,Typhoon,AmphTransport,Boris,Desolator,TerrorDrone,SeaScorpion

[Objective.1]
Text=摧毁超时空仪
TextEn=Destroy Chronosphere
Primary=yes
GateWin=yes

[Trig.1]
Cond=Always
Act=Objective
Msg=阿拉斯加：摧毁盟军超时空仪。
MsgEn=Alaska: destroy Allied Chronosphere.

[Trig.2]
Cond=Always
Act=Eva
Msg=阿拉斯加：摧毁盟军超时空仪。
MsgEn=Alaska: destroy Allied Chronosphere.

[Trig.3]
Cond=Always
Act=SetPhase
A0=1

[Trig.4]
Cond=PlayerAllDead
Act=Lose
C0=0
Msg=我军覆灭。
MsgEn=Our forces destroyed.

[Trig.5]
Cond=PlayerBldLost
Act=CompleteObj
C0=1
BType=ChronoSphere
A0=0
Msg=超时空仪摧毁！
MsgEn=Chronosphere destroyed!

[Trig.6]
Cond=Time
Act=Reinforce
C0=2400
A0=1
A1=0
A2=60
A3=40
Units=Chrono,PrismTank
Once=yes

