; Full scripted: Escape Velocity
[General]
Name=逃逸速度
NameEn=Escape Velocity
Brief=太平洋岛：摧毁尤里潜艇船坞。
BriefEn=Pacific isle: destroy Yuri submarine pens.
Faction=Soviet
AI=Yuri
MapSize=96
MapType=0
Money=13500
Objective=2
ObjectiveTick=0
MapFile=maps/official/ys05.txt
NoStartForce=yes
Track=1
LineId=ys
LineIndex=4
Country=Russia
WinOnAllPrimary=yes
Phase=0
AllowedBuildings=ConYard,TeslaReactor,Barracks,OreRefinery,SentryGun,Wall,WarFactory,NavalYard,Radar,BattleLab,TeslaCoil,FlakCannon,IronCurtain,NukeSilo,ServiceDepot,BattleBunker,TankBunker
AllowedUnits=MCV,Harvester,WarMiner,Conscript,Engineer,AttackDog,FlakTrooper,TeslaTrooper,Rhino,FlakTrack,V3Launcher,Apocalypse,Kirov,Dreadnought,Typhoon,AmphTransport,Boris,Desolator,TerrorDrone,SeaScorpion

[Objective.1]
Text=摧毁潜艇船坞
TextEn=Destroy sub pens
Primary=yes
GateWin=yes

[Objective.2]
Text=摧毁尤里指挥部
TextEn=Destroy Yuri HQ
Primary=yes
GateWin=yes

[Trig.1]
Cond=Always
Act=Objective
Msg=太平洋岛：摧毁尤里潜艇船坞。
MsgEn=Pacific isle: destroy Yuri submarine pens.

[Trig.2]
Cond=Always
Act=Eva
Msg=太平洋岛：摧毁尤里潜艇船坞。
MsgEn=Pacific isle: destroy Yuri submarine pens.

[Trig.3]
Cond=Always
Act=SetPhase
A0=1

[Trig.4]
Cond=PlayerAllDead
Act=Lose
C0=0
Msg=我军覆灭。
MsgEn=Our forces destroyed.

[Trig.5]
Cond=PlayerBldLost
Act=CompleteObj
C0=1
BType=NavalYard
A0=0
Msg=船坞摧毁！
MsgEn=Pens destroyed!

[Trig.6]
Cond=PlayerBldLost
Act=SetPhase
C0=1
BType=NavalYard
A0=2

[Trig.7]
Cond=PlayerBldLost
Act=CompleteObj
C0=1
BType=ConYard
A0=1
RequiresPhase=2
Msg=岛屿肃清！
MsgEn=Isle cleared!

