; Full scripted: To the Moon
[General]
Name=奔向月球
NameEn=To the Moon
Brief=月球：摧毁月球指挥中心。
BriefEn=The Moon: destroy lunar command center.
Faction=Soviet
AI=Yuri
MapSize=96
MapType=0
Money=14000
Objective=2
ObjectiveTick=0
MapFile=maps/official/ys06.txt
NoStartForce=yes
Track=1
LineId=ys
LineIndex=5
Country=Russia
WinOnAllPrimary=yes
Phase=0
AllowedBuildings=ConYard,TeslaReactor,Barracks,OreRefinery,SentryGun,Wall,WarFactory,NavalYard,Radar,BattleLab,TeslaCoil,FlakCannon,IronCurtain,NukeSilo,ServiceDepot,BattleBunker,TankBunker
AllowedUnits=MCV,Harvester,WarMiner,Conscript,Engineer,AttackDog,FlakTrooper,TeslaTrooper,Rhino,FlakTrack,V3Launcher,Apocalypse,Kirov,Dreadnought,Typhoon,AmphTransport,Boris,Desolator,TerrorDrone,SeaScorpion

[Objective.1]
Text=摧毁月球指挥中心
TextEn=Destroy lunar command
Primary=yes
GateWin=yes

[Trig.1]
Cond=Always
Act=Objective
Msg=月球：摧毁月球指挥中心。
MsgEn=The Moon: destroy lunar command center.

[Trig.2]
Cond=Always
Act=Eva
Msg=月球：摧毁月球指挥中心。
MsgEn=The Moon: destroy lunar command center.

[Trig.3]
Cond=Always
Act=SetPhase
A0=1

[Trig.4]
Cond=PlayerAllDead
Act=Lose
C0=0
Msg=我军覆灭。
MsgEn=Our forces destroyed.

[Trig.5]
Cond=PlayerBldLost
Act=CompleteObj
C0=1
BType=ConYard
A0=0
Msg=月球基地摧毁！
MsgEn=Lunar base destroyed!

[Trig.6]
Cond=Time
Act=Reinforce
C0=3000
A0=1
A1=1
A2=50
A3=40
Units=FloatingDisc,Initiate
Once=yes

